name: Auto Assign Reviewer

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
    - name: Auto-assign reviewer
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.DISCORD_PAT }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
        -d '{"reviewers":["t-rhex","johnychhantyal2"]}'